#!/bin/bash
set -e

# parse arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --config-file)
    CONFIG_FILE="$2"
    shift # past argument
    shift # past value
    ;;
    --samples-file)
    SAMPLES_FILE="$2"
    shift # past argument
    shift # past value
    ;;
    --image-dir)
    IMAGE_DIR="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done

# parse config file and assign parameters to variables
eval "$(jq -r "to_entries|map(\"export \(.key)=\(.value|tostring)\")|.[]" $CONFIG_FILE)"

# create train job dir
TIMESTAMP=$(date +%Y_%m_%d_%H_%M_%S)
TRAIN_JOB_DIR=train_jobs/$TIMESTAMP
mkdir -p $TRAIN_JOB_DIR

# copy config and samples file to train job dir
cp $CONFIG_FILE $TRAIN_JOB_DIR/config.json
cp $SAMPLES_FILE $TRAIN_JOB_DIR/samples.json

# start training
DOCKER_RUN="docker run -d
  -v $IMAGE_DIR:/src/images
  -v "$(pwd)/$TRAIN_JOB_DIR":/src/$TRAIN_JOB_DIR
  -e TRAIN_JOB_DIR=$TRAIN_JOB_DIR
  $docker_image"

eval $DOCKER_RUN

# stream logs from container
CONTAINER_ID=$(docker ps -l -q)
docker logs $CONTAINER_ID --follow
